baseurl: "https://media.ikovylyaev.com" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

project: ""
